---
apiVersion: v1
kind: Namespace
metadata:
  name: poc-ns
spec: { }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: poc-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeName: kind-control-plane
      containers:
        - name: nginx
          image: nginx:1.16
